spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/sogong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9082



